############################################# SCHEMA #############################################


############################################# DATA #############################################


############################################# QUERY #############################################
#Write a query to find the friends of Brandon’s friends


#Create a rule to infer two people may be acquaintances based on mutual friends

