############################################# SCHEMA #############################################


############################################# DATA #############################################


############################################# QUERY #############################################
#Who is in queue before Alexis?


#Who is in queue after the person after Bob?


#Who is the last person in the queue?

