type header.txt ..\sql\defining-schema.sql middle.txt ..\graql\defining-schema.gql footer.txt > ..\side-by-side\defining-schema.md
type header.txt ..\sql\deleting-data.sql middle.txt ..\graql\deleting-data.gql footer.txt > ..\side-by-side\deleting-data.md
type header.txt ..\sql\modifying-data.sql middle.txt ..\graql\modifying-data.gql footer.txt > ..\side-by-side\modifying-data.md
type header.txt ..\sql\inner-join.sql middle.txt ..\graql\inner-join.gql footer.txt > ..\side-by-side\inner-join.md
type header.txt ..\sql\insert-data.sql middle.txt ..\graql\insert-data.gql footer.txt > ..\side-by-side\insert-data.md
type header.txt ..\sql\associate-data.sql middle.txt ..\graql\associate-data.gql footer.txt > ..\side-by-side\associate-data.md
type header.txt ..\sql\intersect.sql middle.txt ..\graql\intersect.gql footer.txt > ..\side-by-side\intersect.md
type header.txt ..\sql\left-join.sql middle.txt ..\graql\left-join.gql footer.txt > ..\side-by-side\left-join.md
type header.txt ..\sql\project.sql middle.txt ..\graql\project.gql footer.txt > ..\side-by-side\project.md
type header.txt ..\sql\restrict.sql middle.txt ..\graql\restrict.gql footer.txt > ..\side-by-side\restrict.md
type header.txt ..\sql\full-outer-join.sql middle.txt ..\graql\full-outer-join.gql footer.txt > ..\side-by-side\full-outer-join.md
type header.txt ..\sql\union.sql middle.txt ..\graql\union.gql footer.txt > ..\side-by-side\union.md